source 'https://rubygems.org'
ruby '2.2.3'

gem 'sinatra', '~> 1.4', '>= 1.4.6'
gem 'haml', '~> 4.0', '>= 4.0.7'
gem 'dm-sqlite-adapter', '~> 1.2'
gem 'datamapper', '~> 1.2'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'